name: dev-deploy

on:
  push:
    branches: [master]
    paths:
      - "api/**"
      - ".github/**"
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1

  ECS_CLUSTER: default
  ECS_SERVICE: memetrics-test-server
  REPOSITORY: 306094223949.dkr.ecr.us-east-1.amazonaws.com/memetrics-dev
  IMAGE_TAG: beta

jobs:
  build:
    name: Deploy dev image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      # - name: Set SSH agent
      #   uses: webfactory/ssh-agent@v0.7.0
      #   with:
      #     log-public-key: true
      #     ssh-private-key: |
      #       ${{ secrets.NEI_SSH }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push to ECR
        uses: docker/build-push-action@v4
        with:
          # builder: ${{ steps.buildx.outputs.name }}
          context: ./api
          file: ./api/Dockerfile
          push: true
          # ssh: default
          target: run
          tags: "${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}"

      - name: Force deployment to ECS
        run: aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service ${{ env.ECS_SERVICE }} --force-new-deployment
